# Generated by Django 5.1.7 on 2025-03-21 19:53

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PitchDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="pitchdeck/profiles/"),
                ),
                ("pitch", models.TextField(max_length=500)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tech", "Technology"),
                            ("finance", "Finance"),
                            ("health", "Healthcare"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                            ("retail", "Retail"),
                            ("manufacturing", "Manufacturing"),
                            ("real_estate", "Real Estate"),
                            ("transportation", "Transportation"),
                            ("energy", "Energy"),
                            ("agriculture", "Agriculture"),
                            ("hospitality", "Hospitality"),
                            ("construction", "Construction"),
                            ("legal", "Legal"),
                            ("marketing", "Marketing"),
                            ("media", "Media"),
                            ("non_profit", "Non-Profit"),
                            ("sports", "Sports"),
                            ("telecommunications", "Telecommunications"),
                            ("utilities", "Utilities"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
