# Generated by Django 5.1.7 on 2025-03-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitchdeck", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pitchdeck",
            name="country",
        ),
        migrations.RemoveField(
            model_name="pitchdeck",
            name="profile_image",
        ),
    ]
