# Generated by Django 5.1.7 on 2025-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pitchdeck", "0002_remove_pitchdeck_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitchdeck",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitchdeck",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitchdeck",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitchdeck",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitchdeck",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pitchdeck",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
